############################################################
# Copyright (c) 2026 Igor Sadza
# Released under the GPLv3 license
# ----------------------------------------------------------
#
# FILE: ./.releaserc.yml
# DESC: Semantic-Release configuration
#
############################################################

##############################################################################
# Options
# https://semantic-release.gitbook.io/semantic-release/usage/configuration#options

# Allow releasing from develop branch - overriding default github plugins
branches:
  - develop

# Continuous Integration environment verifications. This allows making releases from a local machine.
ci: false 

# Output debugging information.
debug: true

# The objective of the dry-run mode is to get a preview of the pending release.
dryRun: false

##############################################################################
# Plugins
# https://semantic-release.gitbook.io/semantic-release/extending/plugins-list#official-plugins

plugins:

  # Plugin to analyze commits with conventional-changelog
  - path: '@semantic-release/commit-analyzer'
    preset: "conventionalcommits"
    releaseRules:
    - { breaking: true, release: major }
    - { type: build,    release: patch }
    - { type: chore,    release: false }
    - { type: ci,       release: false }
    - { type: cicd,     release: false }
    - { type: dep,      release: patch }
    - { type: docs,     release: patch }
    - { type: feat,     release: minor }
    - { type: fix,      release: patch }
    - { type: perf,     release: patch }
    - { type: refactor, release: false }
    - { type: revert,   release: patch }
    - { type: style,    release: patch }
    - { type: test,     release: false }

#-----------------------------------------------------------------------------

  # Plugin to generate changelog content with conventional-changelog
  - path: '@semantic-release/release-notes-generator'
    preset: "conventionalcommits"
    presetConfig:
      types:
        - { type: 'feat',     section: '> Features' }
        - { type: 'fix',      section: '> Fixes' }
        - { type: 'build',    section: '> Build' }
        - { type: 'dep',      section: '> Dependencies' }
        - { type: 'perf',     section: '> Performance' }
        - { type: 'revert',   section: '> Reverts' }
        - { type: 'docs',     section: '> Docs' }
        - { type: 'style',    section: '> Style' }
        - { type: 'cicd',     section: '> CI/CD',    hidden: true }
        - { type: 'ci',       section: '> CI/CD',    hidden: true }
        - { type: 'chore',    section: '> Chores',   hidden: true }
        - { type: 'refactor', section: '> Refactor', hidden: true }
        - { type: 'test',     section: '> Tests',    hidden: true }

#-----------------------------------------------------------------------------

  # Plugin to create or update a changelog file.
  - path: '@semantic-release/changelog'
    changelogFile: 'CHANGELOG.md'        

#-----------------------------------------------------------------------------

  # Plugin to execute custom shell commands.
  #- path: "@semantic-release/exec"
  #  verifyReleaseCmd: >
  #    source ./.hacks/bump_release.sh \
  #    && release_hook \
  #      "${nextRelease.version}" \
  #      "${process.env.CI_PROJECT_NAME}"
  #  
  #  successCmd: >
  #    source ./.hacks/bump_release.sh \
  #    && post_release_hook \
  #      "${nextRelease.version}" \
  #      "${process.env.GITLAB_TOKEN}" \
  #      "${nextRelease.notes}" \
  #      "${process.env.CI_PROJECT_NAME}"

#-----------------------------------------------------------------------------

  # Plugin to commit release assets to the project's git repository.
  - path: '@semantic-release/git'
    assets:
    - 'CHANGELOG.md'
    message: "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"

#-----------------------------------------------------------------------------

  # Plugin to publish a Github release.
  - path: '@semantic-release/github'
